#!/bin/sh -e

echo "Post installation of setupcomputer"

# default ssh-agent on X11
if `grep -v '^#' /etc/X11/Xsession.options | grep use-ssh-agent > /dev/null`; then
	sed -i 's/use-ssh-agent/# \0/g' /etc/X11/Xsession.options
fi

# execute all the commands to configure
su arkadefr -s /bin/bash -c "fc-cache -fv" >/dev/null

echo "changing ownership of /home/arkadefr/.* files"
chown -R arkadefr:arkadefr /home/arkadefr/.*

set +e
systemctl is-active systemd-ask-password-wall.service >/dev/null
wall_service_is_active_rc="$?"
if [ "$wall_service_is_active_rc" -eq "0" ]; then
	systemctl stop systemd-ask-password-wall.service
fi
systemctl is-enabled systemd-ask-password-wall.service >/dev/null
wall_service_is_enabled_rc="$?"
if [ "$wall_service_is_enabled_rc" -eq "0" ]; then
	systemctl disable systemd-ask-password-wall.service
fi
set -e

# create the /var/log/deployment
if ! [ -e /var/log/deployment ]; then
	mkdir /var/log/deployment
	chown arkadefr:root /var/log/deployment
	chmod 0750 /var/log/deployment
fi
