#!/bin/sh -e

if [ remove = "$1" -o abort-install = "$1" -o disappear = "$1" ]; then
	dpkg-divert --package setupcomputer --remove --rename --divert /etc/xdg/awesome/rc.lua.real /etc/xdg/awesome/rc.lua
	dpkg-divert --package setupcomputer --remove --rename --divert /usr/share/awesome/themes/default/theme.lua.real /usr/share/awesome/themes/default/theme.lua
fi
