#!/bin/sh -e

dpkg-divert --package setupcomputer --add --rename --divert /etc/xdg/awesome/rc.lua.real /etc/xdg/awesome/rc.lua
dpkg-divert --package setupcomputer --add --rename --divert /usr/share/awesome/themes/default/theme.lua.real /usr/share/awesome/themes/default/theme.lua
