#!/bin/bash
set -e

PATH_FILE=$1
COMMIT_TYPE=$2
COMMIT_SHA1=$3

BRANCH_NAME=$(git symbolic-ref --short HEAD)
if [[ $BRANCH_NAME =~ ^[0-9]+-.* ]]; then
	if [ -z $3 ]; then
		# if we are not amended the commit
		GITHUB_ISSUE="${BRANCH_NAME%%-*}"
		sed -i.bak -e "1s/^/ref #${GITHUB_ISSUE} - /" $1
	fi
else
	echo "This branch is not related to github issue, will not prepare the commit-msg"
fi
